### ISSUE TITLE
Invalid state root

### ISSUE THREAD

**Issue by alanpoon** [alanpoon/substrate_rsrl#1]
0: sp_panic_handler::panic_hook
             at vendor/substrate/primitives/panic-handler/src/lib.rs:148
   1: sp_panic_handler::set::{{closure}}
             at vendor/substrate/primitives/panic-handler/src/lib.rs:58
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   3: rust_begin_unwind
             at src/libstd/panicking.rs:375
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
   5: core::result::unwrap_failed
             at src/libcore/result.rs:1188
   6: core::result::Result<T,E>::expect
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/result.rs:983
   7: <sp_state_machine::ext::Ext<H,N,B> as sp_externalities::Externalities>::original_storage_hash
             at vendor/substrate/primitives/state-machine/src/ext.rs:196
   8: sc_executor::wasm_runtime::RuntimesCache::fetch_runtime
             at vendor/substrate/client/executor/src/wasm_runtime.rs:114
   9: sc_executor::native_executor::NativeExecutor<D>::with_runtime::{{closure}}
             at vendor/substrate/client/executor/src/native_executor.rs:145
  10: std::thread::local::LocalKey<T>::try_with
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/thread/local.rs:262
  11: std::thread::local::LocalKey<T>::with
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/thread/local.rs:239
  12: sc_executor::native_executor::NativeExecutor<D>::with_runtime
             at vendor/substrate/client/executor/src/native_executor.rs:143
  13: <sc_executor::native_executor::NativeExecutor<D> as sc_executor::RuntimeInfo>::runtime_version
             at vendor/substrate/client/executor/src/native_executor.rs:187
  14: <sc_client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::runtime_version
             at vendor/substrate/client/src/call_executor.rs:200
  15: sc_client::client::Client<B,E,Block,RA>::runtime_version_at
             at vendor/substrate/client/src/client.rs:386
  16: <sc_client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::runtime_version_at
             at vendor/substrate/client/src/client.rs:1570
  17: sp_session::runtime_decl_for_SessionKeys::generate_session_keys_call_api_at
             at vendor/substrate/primitives/session/src/lib.rs:30
  18: <node_template_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_session::SessionKeys<__SR_API_BLOCK__>>::SessionKeys_generate_session_keys_runtime_api_impl::{{closure}}
             at runtime/src/lib.rs:301
  19: node_template_runtime::RuntimeApiImpl<Block,C>::call_api_at
             at runtime/src/lib.rs:301
  20: <node_template_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_session::SessionKeys<__SR_API_BLOCK__>>::SessionKeys_generate_session_keys_runtime_api_impl
             at runtime/src/lib.rs:301
  21: sp_session::SessionKeys::generate_session_keys
             at vendor/substrate/primitives/session/src/lib.rs:30
  22: sp_session::generate_initial_session_keys
             at vendor/substrate/primitives/session/src/lib.rs:65
  23: sc_service::builder::ServiceBuilder<TBl,TRtApi,TGen,TCSExt,sc_client::client::Client<TBackend,TExec,TBl,TRtApi>,alloc::sync::Arc<sc_network::on_demand_layer::OnDemand<TBl>>,TSc,TImpQu,alloc::boxed::Box<dyn sc_network::config::FinalityProofRequestBuilder<TBl>+core::marker::Sync+core::marker::Send>,alloc::sync::Arc<dyn sc_network::chain::FinalityProofProvider<TBl>>,TNetP,TExPool,TRpc,TBackend>::build
             at vendor/substrate/client/service/src/builder.rs:800
  24: node_template::service::new_full
             at node/src/service.rs:77
  25: core::ops::function::FnOnce::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/ops/function.rs:232
  26: sc_cli::runtime::run_service_until_exit
             at vendor/substrate/client/cli/src/runtime.rs:124
  27: sc_cli::run_node
             at vendor/substrate/client/cli/src/lib.rs:345
  28: sc_cli::params::RunCmd::run
             at vendor/substrate/client/cli/src/params.rs:990
  29: sc_cli::run
             at vendor/substrate/client/cli/src/lib.rs:238
  30: node_template::command::run
             at node/src/command.rs:37
  31: node_template::main
             at node/src/main.rs:26
  32: std::rt::lang_start::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  33: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  34: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  35: std::panicking::try
             at src/libstd/panicking.rs:270
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  36: std::rt::lang_start
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  37: main
  38: __libc_start_main
  39: _start

Thread 'main' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0xd06e077b651f066b13b5ec38959a4aa29a371b1365a786a9bc68aa718b834650"', src/libcore/result.rs:1188
when https://gist.github.com/alanpoon/f28a6295d3a492fa38b890a02a639da7#file-substrate_client_db_src_lib-rs-L1621

**Comment by alanpoon** [comment]
Fixed by added the following to mine_loop.
import_block.storage_changes = Some(proposal.storage_changes);
